### ISSUE TITLE
Workaround When Offline?

### ISSUE THREAD

**Issue by homestar9** [commandbox-modules/commandbox-update-check#2]
The readme states that an internet connection is required to use the update check.  However, I ran into an issue where I was using my laptop in an area with no internet service and Commandbox wouldn't start up and I had to CTRL+C my way back to the Windows command prompt.

What do you think about wrapping line 40 of `ModuleConfig.cfc` in a try/catch block so that if for some reason the update check can't reach the internet, it will print a friendly message to the console telling the user to pay their WiFi bill or something? That way, at least Commandbox will start up even if the update check fails.

I made an animation of the issue:
![commandbox](https://user-images.githubusercontent.com/5341142/67531112-2a6ef780-f676-11e9-8686-ba5a229709ae.gif)

**Comment by bdw429s** [comment]
That sounds like a great enhancement.  Normally that error wouldn't totally blow up the CLI, but the interceptor runs inside of the `onCLIStart` method which is outside of the typical error handling so any uncaught errors there will stop the shell from loading.

**Comment by homestar9** [comment]
Yeah, see your point. I tried messing around with changing the file locally to see if I could catch the error and exit gracefully, but it did not work.

I wonder if `onCLIStart` could be wrapped around a try/catch? Then again, it might be beneficial to  have Commandbox halt in the event of a catastrophic error.  That's a tricky issue!

Here's a possible workaround:
1. Type `box config set modules.commandbox-update-check.enable=false`
2. When it returns you to the command prompt, type `box` to start Commandbox.

However be sure to keep `box config set modules.commandbox-update-check.enable=false` written down somewhere because if you don't have internet you won't be able to look it up!

**Comment by bdw429s** [comment]
@homestar9 I think your original idea of putting a try/catch around the code in `ModuleConfig.cfc` is fine to be clear.  I was just providing backstory.  I would just wrap the entire contents of the `onCLIStart` method in a try and in the catch simply output a message saying the update couldn't be performed and then maybe include the error/detail. That way the user knows it tried and failed.

**Comment by homestar9** [comment]
Thanks Brad. I'll get a PR ready.
